# Generated by Django 5.2.18 on 2026-10-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_seat_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date', '-id']},
        ),
    ]
